services:
  nginx:
    image: nginx
    restart: always
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: "true"
    volumes:
      - ./src:/app
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/log:/var/log/nginx
    ports:
      - 8080:80
  php:
    build: ./container/php
    restart: always
    volumes:
      - ./src:/app
      - ./container/php/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    logging:
      driver: none
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
  goaccess:
    image: allinurl/goaccess
    profiles: ["goaccess"]
    ports:
      - 7890:7890
    volumes:
      - ./tmp/log:/var/log/nginx:ro
      - ./container/goaccess/.goaccessrc:/root/.goaccessrc
      - ./tmp/html:/html
    command: /var/log/nginx/access.log --real-time-html -o /html/index.html
  goaccessweb:
    image: nginx
    profiles: ["goaccess"]
    logging:
      driver: none
    ports:
      - 6060:80
    volumes:
      - ./tmp/html:/usr/share/nginx/html