services:
  nginx:
    image: nginx
    restart: always
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: "true"
    volumes:
      - ./src:/app
      - ./container/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php:
    image: php:8.1-fpm
    volumes:
      - ./src:/app
      - ./container/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf